##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Apr 29 11:50:46 2025
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690T-FFG1761
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8KTF51264HZ-1G9
## Data Width: 64
## Time Period: 1250
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L6P_T0_15 
set_property VCCAUX_IO DONTCARE [get_ports {init_calib_complete}]
set_property IOSTANDARD LVCMOS18 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN AM39 [get_ports {init_calib_complete}]

